/*
 * codegen.c - LLVM IR Code Generation (manual, no LLVM API)
 *
 * Walks the AST and emits valid LLVM IR text to a .ll file.
 *
 * IR conventions used:
 *   - Each DSL variable maps to an alloca i32 in @main's entry block.
 *   - SSA temporaries are named %t0, %t1, ... (counter in ctx).
 *   - print  ->  call i32 (i8*, ...) @printf with "%d\n" format string.
 *   - Integer arithmetic uses add/sub/mul/sdiv on i32.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "codegen.h"
#include "ast.h"
#include "symbol_table.h"

/* -------------------------------------------------------
   Forward declarations of internal helpers
   ------------------------------------------------------- */
static int  emit_expr(CodegenCtx *ctx, ASTNode *node);
static void emit_stmt(CodegenCtx *ctx, ASTNode *node);

/* -------------------------------------------------------
   codegen_create
   ------------------------------------------------------- */
CodegenCtx *codegen_create(const char *out_path, SymbolTable *sym) {
    CodegenCtx *ctx = (CodegenCtx *)malloc(sizeof(CodegenCtx));
    if (!ctx) { fprintf(stderr, "[Codegen] Out of memory\n"); exit(1); }

    ctx->out = fopen(out_path, "w");
    if (!ctx->out) {
        fprintf(stderr, "[Codegen] Cannot open output file: %s\n", out_path);
        exit(1);
    }
    ctx->sym         = sym;
    ctx->tmp_counter = 0;
    return ctx;
}

/* -------------------------------------------------------
   codegen_destroy
   ------------------------------------------------------- */
void codegen_destroy(CodegenCtx *ctx) {
    if (ctx->out) fclose(ctx->out);
    free(ctx);
}

/* -------------------------------------------------------
   next_tmp: allocate the next SSA virtual register name
   Returns the register index; caller formats as %t<n>
   ------------------------------------------------------- */
static int next_tmp(CodegenCtx *ctx) {
    return ctx->tmp_counter++;
}

/* -------------------------------------------------------
   emit_header: module-level declarations
   ------------------------------------------------------- */
static void emit_header(CodegenCtx *ctx) {
    FILE *f = ctx->out;
    fprintf(f, "; ============================================================\n");
    fprintf(f, "; LLVM IR generated by DSL Compiler\n");
    fprintf(f, "; ============================================================\n\n");

    fprintf(f, "source_filename = \"dsl_program\"\n");
    fprintf(f, "target datalayout = \"e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128\"\n\n");

    /* Declare external printf */
    fprintf(f, "; External printf declaration\n");
    fprintf(f, "declare i32 @printf(i8* nocapture readonly, ...)\n\n");

    /* Format string: \"%d\\n\" */
    fprintf(f, "; Format string for print\n");
    fprintf(f, "@fmt = private unnamed_addr constant [4 x i8] c\"%%d\\0A\\00\", align 1\n\n");
}

/* -------------------------------------------------------
   emit_allocas: alloca for every variable in symbol table
   ------------------------------------------------------- */
static void emit_allocas(CodegenCtx *ctx) {
    FILE *f = ctx->out;
    fprintf(f, "  ; --- Variable allocations ---\n");
    for (int i = 0; i < SYM_TABLE_SIZE; i++) {
        SymEntry *e = ctx->sym->buckets[i];
        while (e) {
            fprintf(f, "  %%%s = alloca i32, align 4\n", e->name);
            e = e->next;
        }
    }
    fprintf(f, "\n");
}

/* -------------------------------------------------------
   emit_expr: emit IR for an expression node.
   Returns the SSA register index holding the result.
   ------------------------------------------------------- */
static int emit_expr(CodegenCtx *ctx, ASTNode *node) {
    FILE *f = ctx->out;
    int   t;

    switch (node->type) {

        /* Integer constant */
        case NODE_NUMBER:
            t = next_tmp(ctx);
            fprintf(f, "  %%t%d = add i32 0, %d\n", t, node->ival);
            return t;

        /* Variable load */
        case NODE_VAR:
            t = next_tmp(ctx);
            fprintf(f, "  %%t%d = load i32, i32* %%%s, align 4\n",
                    t, node->name);
            return t;

        /* Binary operation */
        case NODE_BINOP: {
            int lreg = emit_expr(ctx, node->binop.left);
            int rreg = emit_expr(ctx, node->binop.right);
            t = next_tmp(ctx);

            const char *op_ir;
            switch (node->binop.op) {
                case OP_ADD: op_ir = "add";  break;
                case OP_SUB: op_ir = "sub";  break;
                case OP_MUL: op_ir = "mul";  break;
                case OP_DIV: op_ir = "sdiv"; break;
                default:     op_ir = "add";  break;
            }
            fprintf(f, "  %%t%d = %s i32 %%t%d, %%t%d\n",
                    t, op_ir, lreg, rreg);
            return t;
        }

        default:
            fprintf(stderr, "[Codegen] Unexpected expression node type %d\n",
                    node->type);
            exit(1);
    }
}

/* -------------------------------------------------------
   emit_stmt: emit IR for a statement node
   ------------------------------------------------------- */
static void emit_stmt(CodegenCtx *ctx, ASTNode *node) {
    FILE *f = ctx->out;

    switch (node->type) {

        /* Assignment: evaluate RHS, store to variable */
        case NODE_ASSIGN: {
            fprintf(f, "  ; assign %s\n", node->assign.var_name);
            int rhs = emit_expr(ctx, node->assign.expr);
            fprintf(f, "  store i32 %%t%d, i32* %%%s, align 4\n",
                    rhs, node->assign.var_name);
            break;
        }

        /* Print: evaluate expression, call printf */
        case NODE_PRINT: {
            fprintf(f, "  ; print\n");
            int val = emit_expr(ctx, node->print.expr);
            int fmtptr = next_tmp(ctx);
            fprintf(f,
                "  %%t%d = getelementptr inbounds [4 x i8], [4 x i8]* @fmt, i32 0, i32 0\n",
                fmtptr);
            int ignored = next_tmp(ctx);
            fprintf(f,
                "  %%t%d = call i32 (i8*, ...) @printf(i8* %%t%d, i32 %%t%d)\n",
                ignored, fmtptr, val);
            break;
        }

        default:
            fprintf(stderr, "[Codegen] Unexpected statement node type %d\n",
                    node->type);
            break;
    }
}

/* -------------------------------------------------------
   codegen_generate: top-level entry point
   ------------------------------------------------------- */
void codegen_generate(CodegenCtx *ctx, ASTNode *root) {
    FILE *f = ctx->out;

    printf("[Codegen] Generating LLVM IR...\n");

    /* Module header */
    emit_header(ctx);

    /* @main function preamble */
    fprintf(f, "define i32 @main() {\n");
    fprintf(f, "entry:\n");

    /* Allocate stack space for every variable */
    emit_allocas(ctx);

    /* Emit code for each statement */
    if (root && root->type == NODE_PROGRAM) {
        for (int i = 0; i < root->program.count; i++) {
            emit_stmt(ctx, root->program.stmts[i]);
        }
    }

    /* Return 0 from main */
    fprintf(f, "\n  ; --- Program exit ---\n");
    fprintf(f, "  ret i32 0\n");
    fprintf(f, "}\n");

    printf("[Codegen] LLVM IR written successfully.\n");
}
